"""Added last_update attribute

Revision ID: 8d834482d454
Revises: f7e8a5aadfb8
Create Date: 2026-05-13 00:19:09.835557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d834482d454'
down_revision: Union[str, Sequence[str], None] = 'f7e8a5aadfb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('container', sa.Column('last_update', sa.DateTime(), nullable=False))
    op.add_column('log_temperature', sa.Column('last_update', sa.DateTime(), nullable=False))
    op.add_column('patient', sa.Column('last_update', sa.DateTime(), nullable=False))
    op.add_column('project_team', sa.Column('last_update', sa.DateTime(), nullable=False))
    op.add_column('protocol', sa.Column('last_update', sa.DateTime(), nullable=False))
    op.add_column('quality_control', sa.Column('last_update', sa.DateTime(), nullable=False))
    op.add_column('research_project', sa.Column('last_update', sa.DateTime(), nullable=False))
    op.add_column('research_project_samples', sa.Column('last_update', sa.DateTime(), nullable=False))
    op.add_column('sample', sa.Column('last_update', sa.DateTime(), nullable=False))
    op.add_column('sample_type', sa.Column('last_update', sa.DateTime(), nullable=False))
    op.add_column('staff', sa.Column('last_update', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'last_update')
    op.drop_column('sample_type', 'last_update')
    op.drop_column('sample', 'last_update')
    op.drop_column('research_project_samples', 'last_update')
    op.drop_column('research_project', 'last_update')
    op.drop_column('quality_control', 'last_update')
    op.drop_column('protocol', 'last_update')
    op.drop_column('project_team', 'last_update')
    op.drop_column('patient', 'last_update')
    op.drop_column('log_temperature', 'last_update')
    op.drop_column('container', 'last_update')
    # ### end Alembic commands ###
