"""Initial schema creation

Revision ID: f7e8a5aadfb8
Revises: 
Create Date: 2026-05-13 00:17:24.666264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7e8a5aadfb8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('container',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('test', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('research_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_name')
    )
    op.create_table('sample_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('researcher', 'analyst', 'technician', 'manager', 'administrator'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('project_team',
    sa.Column('id_project', sa.Integer(), nullable=False),
    sa.Column('id_staff', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('principal_investigator', 'co_investigator', 'analyst', 'technician', 'assistant'), nullable=False),
    sa.ForeignKeyConstraint(['id_project'], ['research_project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_staff'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_project', 'id_staff')
    )
    op.create_table('protocol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('protocol_file', sa.LargeBinary(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('creation_date', sa.Date(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_review_date', sa.Date(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['staff.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('volume', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('extraction_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_process', 'analyzed', 'rejected', 'archived'), nullable=False),
    sa.Column('id_patient', sa.Integer(), nullable=False),
    sa.Column('id_sample_type', sa.Integer(), nullable=False),
    sa.Column('id_container', sa.Integer(), nullable=False),
    sa.CheckConstraint('volume > 0', name='check_volume_positive'),
    sa.ForeignKeyConstraint(['id_container'], ['container.id'], ),
    sa.ForeignKeyConstraint(['id_patient'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['id_sample_type'], ['sample_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('log_temperature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reading_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('id_sample', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_sample'], ['sample.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('concentration', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('result', sa.Enum('approved', 'rejected', 'pending_review'), nullable=False),
    sa.Column('id_sample', sa.Integer(), nullable=False),
    sa.CheckConstraint('concentration >= 0', name='check_concentration_positive'),
    sa.CheckConstraint('purity BETWEEN 0 AND 100', name='check_purity_range'),
    sa.ForeignKeyConstraint(['id_sample'], ['sample.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_sample')
    )
    op.create_table('research_project_samples',
    sa.Column('sample_assignment_date', sa.Date(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id_sample', sa.Integer(), nullable=False),
    sa.Column('id_project', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_project'], ['research_project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_sample'], ['sample.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_sample', 'id_project'),
    sa.UniqueConstraint('id_sample', 'id_project', name='uq_sample_project')
    )
    op.create_table('sample_protocol',
    sa.Column('id_protocol', sa.Integer(), nullable=False),
    sa.Column('id_sample', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_protocol'], ['protocol.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_sample'], ['sample.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_protocol', 'id_sample')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample_protocol')
    op.drop_table('research_project_samples')
    op.drop_table('quality_control')
    op.drop_table('log_temperature')
    op.drop_table('sample')
    op.drop_table('protocol')
    op.drop_table('project_team')
    op.drop_table('staff')
    op.drop_table('sample_type')
    op.drop_table('research_project')
    op.drop_table('patient')
    op.drop_table('container')
    # ### end Alembic commands ###
